# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期'),
        ),
    ]
